# Permalinks
permalink:           pretty

# Setup
title:               Ricky Tse
tagline:             My Data Science Adventure Blog
url:                 http://ct5492.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Ricky Tse
  url:               https://twitter.com/chisingtse
  email:             ctse@qc.cuny.edu

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/ct5492

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
